# Generated by Django 4.2.7 on 2023-12-08 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_students_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
